export * from './NewMovies'
export * from './HomePage/HomePage'
export * from './PopularMovies'
export * from './TopRatedMovies'
export * from './TvShowsPage'
export * from '../components/MovieDetail/MovieDetail'
